[project]
name = "r2x_r2x_pypsa"
version = "0.1.0"
description = "R2X external plugin for r2x_pypsa"
dependencies = ["r2x"]
requires-python = ">=3.10"

[project.entry-points."r2x_plugin"]
r2x_pypsa = "r2x_pypsa.plugin:create_plugin_components"
